apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-operator-serviceaccount
  namespace: aci-containers-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: aci-operator-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: aci-operator-serviceaccount
  namespace: aci-containers-system